name: task1
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  display_name_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: run bash script
      run: |
        chmod +x script.sh
        ./script.sh
